### PR TITLE
Bump to latest Rector 0.18.1

### PR DESCRIPTION
**Pull request by samsonasik**
Hi, this PR bump to Rector 0.8.11 👍

### CODE REVIEW

**Comment by samsonasik** [comment]
@Wirone Ready to merge 👍

**Comment by Wirone** [comment]
Wow, thanks @samsonasik for the contribution 🙂. Please fix the CI problems when you have some time, I'll look at it deeper in the evening.

**Comment by samsonasik** [comment]
@Wirone All green 🎉 Ready to merge 👍

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you very much @samsonasik 🍻!

**Pull request merged**
