### PR TITLE
Bump to Rector ^1.0

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@Wirone Ready to merge 👍

**Comment by Wirone** [comment]
Closing and re-opening to trigger CI, since there was some issue and actions were not run.

**Comment by Wirone** [comment]
Huh? Weird... Why did it stop working 😅?

**Comment by samsonasik** [comment]
Github was down yesterday, so probably today too

**Comment by Wirone** [comment]
Workflows were disabled because of 60 days inactivity 😩.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you @samsonasik 🍻!

**Pull request merged**
